import type { ExerciseClass } from "./types";

/**
 * Slow Stack Pro move library. These classes only enter the rotation when
 * Pro is unlocked, and still respect gear (requiredAsset).
 */
export const PRO_CLASSES: ExerciseClass[] = [
  // CHEST
  {
    classId: "pro-incline-push-family",
    slot: "chest",
    name: "Desk Push Family",
    emoji: "🖥️",
    muscles: ["chest", "shoulders", "arms"],
    proOnly: true,
    bareMinimum: {
      id: "palm-press",
      name: "Palm Press Holds",
      emoji: "🙏",
      cues: [
        "Press palms together at chest height",
        "Squeeze for five seconds, then relax",
        "Shoulders down, breathe steady",
      ],
      reps: 6,
      level: 1,
      note: "Chest wake-up from your chair",
    },
    next: {
      id: "incline-desk-push",
      name: "Incline Desk Push-Ups",
      emoji: "🖥️",
      cues: [
        "Hands on a sturdy desk edge",
        "Walk feet back until body is one line",
        "Lower chest to the edge, press away",
      ],
      reps: 10,
      level: 2,
      note: "Make sure the desk will not slide",
    },
    spunky: {
      id: "archer-push",
      name: "Archer Push-Ups",
      emoji: "🏹",
      cues: [
        "Wide hands, shift weight to one arm",
        "Other arm stays long like a bowstring",
        "Alternate sides",
      ],
      reps: 6,
      level: 5,
      note: "Each side counts as one",
    },
    spunkyOptions: [
      {
        id: "decline-push",
        name: "Decline Push-Ups",
        emoji: "📐",
        cues: [
          "Feet up on a chair or step",
          "Hands under shoulders",
          "Lower slow, press strong",
        ],
        reps: 6,
        level: 4,
        note: "Upper chest gets the love",
      },
    ],
  },

  // LEGS
  {
    classId: "pro-lunge-family",
    slot: "legs",
    name: "Lunge Family",
    emoji: "🚶",
    muscles: ["legs", "glutes", "core"],
    proOnly: true,
    bareMinimum: {
      id: "leg-swings",
      name: "Standing Leg Swings",
      emoji: "🦿",
      cues: [
        "Hold a counter or wall",
        "Swing one leg forward and back, relaxed",
        "Switch sides",
      ],
      reps: 10,
      level: 1,
      note: "Each side, loose and easy",
    },
    next: {
      id: "reverse-lunge",
      name: "Reverse Lunges",
      emoji: "🚶",
      cues: [
        "Step one foot back, lower both knees",
        "Front knee stacks over ankle",
        "Push through the front heel to stand",
      ],
      reps: 10,
      level: 2,
      note: "Alternate legs",
    },
    spunky: {
      id: "bulgarian-split",
      name: "Bulgarian Split Squats",
      emoji: "🪑",
      cues: [
        "Back foot on a chair seat",
        "Lower straight down, torso tall",
        "Drive up through the front foot",
      ],
      reps: 8,
      level: 4,
      note: "Each side",
    },
    spunkyOptions: [
      {
        id: "jump-lunge",
        name: "Jumping Lunges",
        emoji: "⚡",
        cues: [
          "Start in a lunge",
          "Jump and switch legs mid-air",
          "Land soft, knees tracking",
        ],
        reps: 10,
        level: 5,
        note: "Short and spicy",
      },
    ],
  },
  {
    classId: "pro-db-hinge-family",
    slot: "legs",
    name: "Dumbbell Legs",
    emoji: "🏋️",
    muscles: ["legs", "glutes", "back"],
    requiredAsset: "dumbbells",
    proOnly: true,
    bareMinimum: {
      id: "hip-hinge-drill",
      name: "Hip Hinge Drill",
      emoji: "🙇",
      cues: [
        "Hands on hips, soft knees",
        "Push hips back until you feel the hamstrings",
        "Stand tall, squeeze glutes",
      ],
      reps: 8,
      level: 1,
      note: "Pattern first, no weight",
    },
    next: {
      id: "goblet-squat",
      name: "Goblet Squats",
      emoji: "🏆",
      cues: [
        "Hold one dumbbell at your chest",
        "Sit between your heels",
        "Elbows inside knees at the bottom",
      ],
      reps: 10,
      level: 2,
      note: "Light weight is plenty",
    },
    spunky: {
      id: "db-rdl",
      name: "Dumbbell Romanian Deadlifts",
      emoji: "🏋️",
      cues: [
        "Weights slide down the thighs",
        "Flat back, hinge at the hips",
        "Squeeze glutes to stand",
      ],
      reps: 10,
      level: 3,
      note: "Slow on the way down",
    },
  },

  // BACK
  {
    classId: "pro-posture-family",
    slot: "back",
    name: "Desk Posture Family",
    emoji: "🪪",
    muscles: ["back", "shoulders"],
    proOnly: true,
    bareMinimum: {
      id: "chin-tuck",
      name: "Chin Tucks",
      emoji: "🐢",
      cues: [
        "Sit tall, eyes level",
        "Glide chin straight back, making a double chin",
        "Hold two seconds, release",
      ],
      reps: 8,
      level: 1,
      note: "Undo screen neck",
    },
    next: {
      id: "prone-yt",
      name: "Prone Y-T Raises",
      emoji: "🙆",
      cues: [
        "Lie face-down, arms in a Y",
        "Lift thumbs up, then sweep to a T",
        "Shoulder blades do the work",
      ],
      reps: 8,
      level: 2,
      note: "Small lifts are fine",
    },
    spunky: {
      id: "reverse-angel",
      name: "Reverse Snow Angels",
      emoji: "👼",
      cues: [
        "Face-down, arms hovering by your hips",
        "Sweep arms overhead without touching down",
        "Sweep back, chest slightly lifted",
      ],
      reps: 8,
      level: 3,
      note: "Slow sweeps, long neck",
    },
  },
  {
    classId: "pro-bar-skills-family",
    slot: "back",
    name: "Bar Skills",
    emoji: "🪝",
    muscles: ["back", "arms", "core"],
    requiredAsset: "hangBar",
    proOnly: true,
    bareMinimum: {
      id: "active-hang",
      name: "Active Hang",
      emoji: "🪝",
      cues: [
        "Hang, then pull shoulders slightly down",
        "Arms stay straight",
        "Hold and breathe",
      ],
      durationSec: 15,
      level: 2,
      note: "Feet can touch a chair if needed",
    },
    next: {
      id: "hanging-knee-raise",
      name: "Hanging Knee Raises",
      emoji: "🦵",
      cues: [
        "Hang with shoulders engaged",
        "Lift knees toward chest",
        "Lower with control, no swinging",
      ],
      reps: 6,
      level: 3,
      note: "Back and abs together",
    },
    spunky: {
      id: "chin-up",
      name: "Chin-Ups",
      emoji: "💪",
      cues: [
        "Palms facing you, shoulder-width",
        "Pull chin over the bar",
        "Slow lower all the way",
      ],
      reps: 4,
      level: 5,
      note: "Negatives count too",
    },
  },

  // ABS
  {
    classId: "pro-hollow-family",
    slot: "abs",
    name: "Hollow Family",
    emoji: "🥄",
    muscles: ["core"],
    proOnly: true,
    bareMinimum: {
      id: "seated-knee-lift",
      name: "Seated Knee Lifts",
      emoji: "🪑",
      cues: [
        "Sit tall near the chair edge",
        "Lift one knee a few inches, lower slow",
        "Alternate sides",
      ],
      reps: 10,
      level: 1,
      note: "Desk-friendly core",
    },
    next: {
      id: "hollow-tuck",
      name: "Hollow Tuck Hold",
      emoji: "🥄",
      cues: [
        "On your back, knees tucked, shoulders lifted",
        "Low back pressed into the floor",
        "Breathe, hold",
      ],
      durationSec: 20,
      level: 2,
      note: "Shape over duration",
    },
    spunky: {
      id: "v-up",
      name: "V-Ups",
      emoji: "✌️",
      cues: [
        "Lie long, arms overhead",
        "Lift legs and torso to meet in the middle",
        "Lower slow",
      ],
      reps: 8,
      level: 4,
      note: "Bent knees is fine",
    },
  },
  {
    classId: "pro-side-core-family",
    slot: "abs",
    name: "Side Core",
    emoji: "📏",
    muscles: ["core", "shoulders"],
    proOnly: true,
    bareMinimum: {
      id: "standing-side-bend",
      name: "Standing Side Bends",
      emoji: "🌾",
      cues: [
        "Feet hip-width, one arm overhead",
        "Lean gently to the side",
        "Alternate, slow breaths",
      ],
      reps: 8,
      level: 1,
      note: "Each side",
    },
    next: {
      id: "knee-side-plank",
      name: "Knee Side Plank",
      emoji: "📏",
      cues: [
        "Elbow under shoulder, knees bent",
        "Lift hips to a straight line",
        "Switch sides",
      ],
      durationSec: 20,
      level: 2,
      note: "Each side",
    },
    spunky: {
      id: "side-plank-dip",
      name: "Side Plank Hip Dips",
      emoji: "🌊",
      cues: [
        "Full side plank on your forearm",
        "Lower hip toward the floor, lift back up",
        "Switch sides",
      ],
      reps: 8,
      level: 4,
      note: "Each side",
    },
  },

  // MOBILITY
  {
    classId: "pro-desk-reset-family",
    slot: "mobility",
    name: "Desk Reset",
    emoji: "⌨️",
    muscles: ["arms", "legs", "glutes"],
    proOnly: true,
    bareMinimum: {
      id: "wrist-stretch",
      name: "Wrist & Forearm Stretch",
      emoji: "✋",
      cues: [
        "Arm out, palm up, gently pull fingers back",
        "Then palm down, fingers toward you",
        "Switch arms",
      ],
      durationSec: 30,
      level: 1,
      note: "Typing hands will thank you",
    },
    next: {
      id: "hip-flexor-stretch",
      name: "Standing Hip Flexor Stretch",
      emoji: "🧍",
      cues: [
        "Split stance, back heel lifted",
        "Tuck the tailbone, shift forward",
        "Reach the same-side arm up",
      ],
      durationSec: 40,
      level: 2,
      note: "Each side, sitting antidote",
    },
    spunky: {
      id: "deep-squat-hold",
      name: "Deep Squat Hold",
      emoji: "🧘",
      cues: [
        "Feet wide, toes slightly out",
        "Sink low, elbows press knees open",
        "Hold a counter if you need",
      ],
      durationSec: 45,
      level: 3,
      note: "Breathe into the hips",
    },
  },
];
